# Generated by the Live Palette addon from res://live_palette/*.tres.
# Do not edit — it is rewritten whenever a palette changes.
class_name LivePalette

## The constants are the "Default" variant; switching variants at runtime goes
## through the LivePaletteRuntime autoload, which re-applies bound properties.
const WHITE := Color(0.91764706, 0.8862745, 0.7176471, 1)
const YELLOW := Color(0.9882353, 0.7490196, 0.28627452, 1)
const RED := Color(0.8392157, 0.15686275, 0.15686275, 1)
const ORANGE := Color(0.96862745, 0.49803922, 0, 1)
const LIGHT_GREEN := Color(0.4117647, 0.8627451, 0.61960787, 1)
const LIGHT_BLUE := Color(0.06666667, 0.6156863, 0.6431373, 1)
const DARK_BLUE := Color(0, 0.1882353, 0.28627452, 1)
const GRAY := Color(0.32156864, 0.40392157, 0.44705883, 1)
const OLIVE_LIGHT := Color(0.7764706, 0.7411765, 0.5254902, 1)
const OLIVE := Color(0.6313726, 0.6, 0.41960785, 1)
const OLIVE_DARK := Color(0.45490196, 0.43137255, 0.30980393, 1)

## Palette name -> color, for lookups by a name held in a variable.
## Prefer the constants above: they are checked at compile time.
const BY_NAME := {
	"White": WHITE,
	"Yellow": YELLOW,
	"Red": RED,
	"Orange": ORANGE,
	"Light Green": LIGHT_GREEN,
	"Light Blue": LIGHT_BLUE,
	"Dark Blue": DARK_BLUE,
	"Gray": GRAY,
	"Olive Light": OLIVE_LIGHT,
	"Olive": OLIVE,
	"Olive Dark": OLIVE_DARK,
}

## Variant name -> {name -> color}, for reading a variant you are not on.
const VARIANTS := {
	"Default": {
		"White": Color(0.91764706, 0.8862745, 0.7176471, 1),
		"Yellow": Color(0.9882353, 0.7490196, 0.28627452, 1),
		"Red": Color(0.8392157, 0.15686275, 0.15686275, 1),
		"Orange": Color(0.96862745, 0.49803922, 0, 1),
		"Light Green": Color(0.4117647, 0.8627451, 0.61960787, 1),
		"Light Blue": Color(0.06666667, 0.6156863, 0.6431373, 1),
		"Dark Blue": Color(0, 0.1882353, 0.28627452, 1),
		"Gray": Color(0.32156864, 0.40392157, 0.44705883, 1),
		"Olive Light": Color(0.7764706, 0.7411765, 0.5254902, 1),
		"Olive": Color(0.6313726, 0.6, 0.41960785, 1),
		"Olive Dark": Color(0.45490196, 0.43137255, 0.30980393, 1),
	},
}


static func color(p_name: StringName) -> Color:
	var key := str(p_name)
	if BY_NAME.has(key):
		return BY_NAME[key]
	push_warning("LivePalette: no color named '%s'" % p_name)
	return Color.WHITE


static func has_color(p_name: StringName) -> bool:
	return BY_NAME.has(str(p_name))


## A color from a specific variant, falling back to the base variant.
static func color_in(p_variant: StringName, p_name: StringName) -> Color:
	var table: Dictionary = VARIANTS.get(str(p_variant), {})
	if table.has(str(p_name)):
		return table[str(p_name)]
	return color(p_name)


static func variant_names() -> PackedStringArray:
	return PackedStringArray(VARIANTS.keys())


## From res://live_palette/game.tres.
class GAME:
	## The constants are the "Default" variant; switching variants at runtime goes
	## through the LivePaletteRuntime autoload, which re-applies bound properties.
	const SAND := Color(0.9019608, 0.6392157, 0.21176471, 1)
	const BLOOD := Color(0.54901963, 0.03137255, 0.03529412, 1)
	const FUEL := Color(0.11372549, 0.10980392, 0.23529412, 1)

	## Palette name -> color, for lookups by a name held in a variable.
	## Prefer the constants above: they are checked at compile time.
	const BY_NAME := {
		"Sand": SAND,
		"Blood": BLOOD,
		"Fuel": FUEL,
	}

	## Variant name -> {name -> color}, for reading a variant you are not on.
	const VARIANTS := {
		"Default": {
			"Sand": Color(0.9019608, 0.6392157, 0.21176471, 1),
			"Blood": Color(0.54901963, 0.03137255, 0.03529412, 1),
			"Fuel": Color(0.11372549, 0.10980392, 0.23529412, 1),
		},
	}


	static func color(p_name: StringName) -> Color:
		var key := str(p_name)
		if BY_NAME.has(key):
			return BY_NAME[key]
		push_warning("LivePalette.GAME: no color named '%s'" % p_name)
		return Color.WHITE


	static func has_color(p_name: StringName) -> bool:
		return BY_NAME.has(str(p_name))


	## A color from a specific variant, falling back to the base variant.
	static func color_in(p_variant: StringName, p_name: StringName) -> Color:
		var table: Dictionary = VARIANTS.get(str(p_variant), {})
		if table.has(str(p_name)):
			return table[str(p_name)]
		return color(p_name)


	static func variant_names() -> PackedStringArray:
		return PackedStringArray(VARIANTS.keys())
